name: Makefile CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Install dependencies
      run: pip install -r requirements.txt

    # Run tests
    - name: Run tests
      run: python -m unittest discover -s tests

    # Run linting
    - name: Run linting
      run: flake8 src tests